Add Self-Check List Integration Test
astrod/fosslight pull request #3
Opened 2021-10-13 09:50 UTC by Lee-JaeHyuk

## Description
Add Self-Check List Integration Test

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-10-15 10:17 UTC, soimkim commented
@Lee-JaeHyuk ,
Please add license and copyright to the top of the file.
ex)
/*
Copyright (c) 2021 JaeHyuk Lee
SPDX-License-Identifier: AGPL-3.0-only
*/

2021-10-15 13:44 UTC, astrod commented on src/test/java/oss/fosslight/controller/SelfCheckControllerTest.java
> +    @DisplayName("Adding Self-Check list should be failed when prjName is empty")
Prjname of above test is also empty(""). I understand what you say. However, what do you think about putting prjName into first test(registrationShouldBeSuccess) ?

2021-10-16 11:50 UTC, astrod commented
@Lee-JaeHyuk . The PR is same as other(https://github.com/astrod/fosslight/pull/2/files). Please reflect my comment and manage two pull request

2021-10-16 11:51 UTC, astrod requested changes
@Lee-JaeHyuk . The PR is same as other(https://github.com/astrod/fosslight/pull/2/files). Please reflect my comment and manage two pull request

2021-10-18 12:29 UTC, astrod commented on src/test/java/oss/fosslight/controller/SelfCheckControllerTest.java
> +package oss.fosslight.controller;
SelfCheckControllerTest and SelfCheckControllerIntegrationTest is same. Please check it, @Lee-JaeHyuk

2021-10-18 14:47 UTC, Lee-JaeHyuk commented on src/test/java/oss/fosslight/controller/SelfCheckControllerTest.java
> +package oss.fosslight.controller;
Yes, I checked. I solved it.

2021-10-19 13:45 UTC, astrod approved these changes
LGTM 👍

2021-10-20 14:03 UTC, merged