Add Project Packing Request Review Integration Test
astrod/fosslight pull request #7
Opened 2021-10-19 00:07 UTC by Lee-JaeHyuk

## Description
Add Project Packing Request Review Integration test

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2021-10-19 13:38 UTC, astrod requested changes
```
    @Test
    void testOssNotice() throws Exception {
        mockMvc.perform(post("/project/verification/saveAjax")
                        .content(EntityUtils.toString(new UrlEncodedFormEntity(Arrays.asList(
                                new BasicNameValuePair("prjId", prj.getPrjId()),
                                new BasicNameValuePair("noticeType", "10"),
                                new BasicNameValuePair("appended", ""),
                                new BasicNameValuePair("appendedTEXT", ""),
                                new BasicNameValuePair("networkServerFlag", "N"),
                                new BasicNameValuePair("setPackageJson", ""),
                                new BasicNameValuePair("setPackageFileId", ""),
                                new BasicNameValuePair("setEditCompanyYn", "Y")
                        ))))
                        .param("useCustomNoticeYn", "N")
                        .param("allowDownloadNoticeHTMLYn", "Y")
                        .param("allowDownloadNoticeTextYn", "N")
                        .param("allowDownloadSimpleHTMLYn", "N")
                        .param("allowDownloadSimpleTextYn", "N")
                        .param("allowDownloadSPDXSheetYn", "N")
                        .param("allowDownloadSPDXRdfYn", "N")
                        .param("allowDownloadSPDXTagYn", "N")
                        .header("user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED))
                .andExpect(status().isOk());
```
Fix the test code like it

2021-10-20 14:00 UTC, astrod approved these changes

2021-10-20 14:02 UTC, astrod commented on src/test/java/oss/fosslight/controller/PackingRequestTest.java
> +    void PackingRequestReviewSuccess() throws Exception{
change uppercase to lowercase at the first letter

2021-10-20 14:02 UTC, astrod commented on src/test/java/oss/fosslight/controller/PackingRequestTest.java
> +    void PackingRequestReviewFail() throws Exception{
change uppercase to lowercase at the first letter

2021-10-21 00:44 UTC, Lee-JaeHyuk commented on src/test/java/oss/fosslight/controller/PackingRequestTest.java
> +    void PackingRequestReviewFail() throws Exception{
i change it

2021-11-08 12:55 UTC, merged